### ISSUE TITLE
v3 REST API documentation: Upload release asset

### ISSUE THREAD

**Issue by gr2m** [octokit/discussions#14]
The current documentation is at https://developer.github.com/v3/repos/releases/#upload-a-release-asset

I find it a bit confusing. It currently says

```
POST https://<upload_url>/repos/:owner/:repo/releases/:id/assets?name=foo.zip
```

I think it should say 

```
POST <upload_url>
```

Because the `upload_url` property as e.g. returned by [Get a single Release](https://developer.github.com/v3/repos/releases/#get-a-single-release) includes the full URL, not just the host name:

[![image](https://user-images.githubusercontent.com/39992/34787420-0a22027e-f5ec-11e7-8fe0-513028f48dd3.png)](https://developer.github.com/v3/repos/releases/#get-a-single-release)

Can we get this changed?

**Comment by kytrinyx** [comment]
I'll post this to the docs team, thanks!

**Comment by Xotl** [comment]
I found this issue while looking for an example. It's also very confusing the [example at octokit/rest.js docs for "Upload a release asset"](https://octokit.github.io/rest.js/#octokit-routes-repos-upload-release-asset). 

Not sure what the headers mean, don't if should i pass in a [Buffer object](https://nodejs.org/api/buffer.html#buffer_class_buffer).

It's very confusing... not sure if i should create another issue in other to get an example. 😕

**Comment by gr2m** [comment]
Here is a test that might help as a reference:
https://github.com/octokit/rest.js/blob/master/test/scenarios/release-assets-test.js

You first need to retrieve the `upload_url` from a release object, which you pass in as the `url` parameter for `octokit.repos.uploadReleaseAsset`. You need to set `content-type` and `content-length` headers. `file` can be a string, a binary or a buffer. In case of `buffer` you don't need to set `content-length` if I recall correctly

**Comment by Xotl** [comment]
Thanks, that helped. 😊

**Comment by gr2m** [comment]
The original issue is no longer relevant, closing
