### ISSUE TITLE
v3 REST API docs: inconsistencies in notifications_url URI templates

### ISSUE THREAD

**Issue by gr2m** [octokit/discussions#15]
Example: [Get repository](https://developer.github.com/v3/repos/#get)

[![image](https://user-images.githubusercontent.com/39992/34787632-c9a601e0-f5ec-11e7-9587-471f58249f2c.png)](https://developer.github.com/v3/repos/#get)

`notification_url` is the only URI template that uses spaces in the `{?since, all, participating}` placeholder. Not in all API endpoints returning `notifications_url`, but in some.

I would suggest we remove the spaces in the docs for consistency.

**Comment by gr2m** [comment]
If it helps I can find all the places where there are spaces, I’ve a crawler that I can adapt for that quite easily

**Comment by kytrinyx** [comment]
Yeah, good point—and if you can find the instances of those, I'll either make the fix or report it to the people who can.

**Comment by gr2m** [comment]
there you go:

- [ ] https://developer.github.com/v3/activity/starring/#list-repositories-being-starred
- [ ] https://developer.github.com/v3/activity/watching/#list-repositories-being-watched
- [ ] https://developer.github.com/v3/apps/installations/#list-repositories
- [ ] https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-user-for-an-installation
- [ ] https://developer.github.com/v3/issues/#list-issues
- [ ] https://developer.github.com/v3/migration/migrations/#get-a-list-of-migrations
- [ ] https://developer.github.com/v3/migration/migrations/#get-the-status-of-a-migration
- [ ] https://developer.github.com/v3/migration/migrations/#start-a-migration
- [ ] https://developer.github.com/v3/orgs/teams/#check-if-a-team-manages-a-repository
- [ ] https://developer.github.com/v3/orgs/teams/#list-team-repos
- [ ] https://developer.github.com/v3/pulls/#create-a-pull-request
- [ ] https://developer.github.com/v3/pulls/#get-a-single-pull-request
- [ ] https://developer.github.com/v3/pulls/#list-pull-requests
- [ ] https://developer.github.com/v3/pulls/#update-a-pull-request
- [ ] https://developer.github.com/v3/pulls/review_requests/#create-a-review-request
- [ ] https://developer.github.com/v3/repos/#create
- [ ] https://developer.github.com/v3/repos/#edit
- [ ] https://developer.github.com/v3/repos/#get
- [ ] https://developer.github.com/v3/repos/#list-organization-repositories
- [ ] https://developer.github.com/v3/repos/#transfer-a-repository
- [ ] https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
- [ ] https://developer.github.com/v3/repos/forks/#create-a-fork
- [ ] https://developer.github.com/v3/repos/forks/#list-forks
- [ ] https://developer.github.com/v3/repos/invitations/#list-a-users-repository-invitations
- [ ] https://developer.github.com/v3/repos/invitations/#list-invitations-for-a-repository
- [ ] https://developer.github.com/v3/repos/invitations/#update-a-repository-invitation

**Comment by kytrinyx** [comment]
Fantastic, thank you!

**Comment by kytrinyx** [comment]
I've submitted a fix.

**Comment by kytrinyx** [comment]
The fix is deployed 🎉

**Comment by gr2m** [comment]
wow that was quick, thanks a ton :)
