### ISSUE TITLE
GitHub-specific URI template parsing

### ISSUE THREAD

**Issue by gr2m** [octokit/discussions#17]
I’ve created a custom URL template parsing library: https://github.com/gr2m/octokit-rest-url-template/blob/initial-version/README.md (not yet released). The main reasons why are

1. `:varname` placeholders are not part of [RFC 6570](https://tools.ietf.org/html/rfc6570), but I’d like it to be able to resolve both `:varname` and `{varname}` placeholders in the URL
2. I needed the list of used variable names, as unused options are passed as query parameters or as request body, see below
3. minimal bundle size for usage in browser. It only implements the parts of RFC 6570 that GitHub is actually using, based on all responses shown on the GitHub API docs, see [full list of GitHub’s URL template variables](https://github.com/gr2m/octokit-rest-url-template/blob/initial-version/README.md#list-of-githubs-url-template-variables)

I’d like to move that repository to the @octokit organization and release it as `@octokit/rest-url-template`, unless there are any objections?

### The longer story

I’ve been thinking a lot about what an Octokit Client library for GitHub’s REST API is at its core, to inform the refactoring of our current Node library: https://github.com/octokit/node-github/pull/692

My conclusion is that at it’s very core it’s turning the options shown in the API docs for an API endpoint into generic request options. Taking [List organization repositories](https://developer.github.com/v3/repos/#list-organization-repositories) as an example, this core method turns these options

<table>
  <tr>
    <th align=left>method</th>
    <td><code>GET</code></td>
  </tr>
  <tr>
    <th align=left>url</th>
    <td><code>/orgs/:org/repos</code></td>
  </tr>
  <tr>
    <td align=left><strong>org</strong> <em>(URL variable)</em></td>
    <td>e.g. <code>octokit</code></td>
  </tr>
  <tr>
    <td align=left><strong>type</strong> <em>(endpoint parameter)</em></td>
    <td>e.g. <code>all</code></td>
  </tr>
  <tr>
    <td align=left><strong>per_page</strong> <em>(pagination parameter)</em></td>
    <td>e.g. <code>20</code></td>
  </tr>
  <tr>
    <td align=left><strong>page</strong> <em>(pagination parameter)</em></td>
    <td>e.g. <code>2</code></td>
  </tr>
</table>

into generic request options that can be passed into any request library or native request API

<table>
  <tr>
    <th align=left>method</th>
    <td><code>GET</code></td>
  </tr>
  <tr>
    <th align=left>url</th>
    <td>e.g. <code>https://api.github.com/orgs/octokit/repos?type=private&per_page=20&page=2</code></td>
  </tr>
</table>

The way it works is the following

1. `method`, `url` and `headers` are passed through to request options
2. Placeholders in `url` are replaced using the remaining options
3. After that if `method` is `GET` or `HEAD`, all remaining options are passed as URL query param option, otherwise remaining options are sent as JSON string in the request body, see [documentation on parameters](https://developer.github.com/v3/#parameters). There are a few exceptions, but that is the general rule. 

The URL template parsing is at the very heart of it and I think that at least for Node, it would be nice to have an officially supported URL template parsing library, because there are so many out there

**Comment by kytrinyx** [comment]
@gr2m I think I'm missing some important piece of context. When you say:

> at it’s very core it’s turning the options shown in the API docs for an API endpoint and turn them into generic request options. Taking List organization repositories as an example, I’d like this core method to turn this [...] into this [...]

I'm not sure where the first JSON snippet comes from, and what you want to use the second snippet for.

**Comment by gr2m** [comment]
sorry maybe the JSON format was not idea, it’s mean to show then endpoint options of [List organization repositories](https://developer.github.com/v3/repos/#list-organization-repositories)

- `GET /orgs/:org/repos` -> `method` and `url`
- Parameters: `type`
- `page` & `per_page` based on the fact that the endpoint returns a list that can be paginated
- I removed `headers` for clarity

does that make sense?

The 2nd snippet shows the options I could pass in to any library that sends http requests

**Comment by bkeepers** [comment]
> …I’d like it to be able to resolve both `:varname` and `{varname}` placeholders in the URL

Just to make sure I understand…

- RFC 6570 expects `{varname}`, like: `/repos/{owner}/{repo}/issues/{number}`
- but the GitHub docs use `:varname`, like: /repos/:owner/:repo/issues/:number`

**Comment by gr2m** [comment]
yes, I wonder why :)

**Comment by gr2m** [comment]
The implementation of my URL replace method is very short by the way, if you want to review the logic, it’s commented, too: https://github.com/gr2m/octokit-rest-url-template/blob/initial-version/index.js

**Comment by bkeepers** [comment]
> I’d like to move that repository to the @octokit organization and release it as `@octokit/rest-url-template`, unless there are any objections?

Doesn't really matter to me. I'd prefer to see us comply with RFCs and reuse libraries that implement them, but I don't think it's a big deal either way in this case.

**Comment by gr2m** [comment]
> I'd prefer to see us comply with RFCs and reuse libraries that implement them

Yes, me too. I couldn't find any existing library that would tell me which variables were used though and I needed that for my implementation of the `@octokit/rest` library. And as I had to redo it anyway myself, I thought why not look into what parts of the RFC GitHub is actually using and implement only that. As I don’t expect any more changes to the REST API I think we are safe.

An alternative would be to somehow contribute that feature back and simply replace all `:varname` with `{varname}` to make the URL template RFC compliant. But I decided it was not worth the effort in this case, it would break the API of any existing library as they all just return a string right now, and none of them keeps track of used variables.

If you’d  feel better about it I can make `@octokit/rest-url-template` fully RFC compliant?

**Comment by kytrinyx** [comment]
I *think* I am starting to see the context, but I still don't understand quite how this would be used.

What is the step between the starting point (knowing what the HTTP verb, path, parameter etc are) and someone using an octokit library to make a call? What would the octokit library know how to do and how would it be used?

> I'd prefer to see us comply with RFCs and reuse libraries that implement them, but I don't think it's a big deal either way in this case.

I think that it would be worth suggesting that we switch the docs to comply with the RFCs.

Even if we don't though, I think it's worth considering using an existing library with a transform step first that substitutes `:varname` with `{varname}`. Not saying we should do that, just wondering if that would be simpler (and less code to maintain).

Minor thing:
>  type (endpoint parameter) | e.g. octokit

_e.g. "all"_ rather than e.g. octokit, I think.

<img width="689" alt="screen shot 2018-01-11 at 4 11 21 pm" src="https://user-images.githubusercontent.com/276834/34852088-31f9c1c0-f6ea-11e7-852d-ea5491bb9ee7.png">

**Comment by gr2m** [comment]
I’m very sorry for my confusing writing. I really appreciate you taking the time to discuss this through, it is helping me a lot :)

> e.g. "all" rather than e.g. octokit, I think.

fixed it, thanks :)

> What is the step between the starting point (knowing what the HTTP verb, path, parameter etc are) and someone using an octokit library to make a call?

The JavaScript Rest library (`@octokit/rest`) has everything included. It has an API like `github.repos.getForOrganization({org: 'octokit', type: 'all', per_page: 20, page: 2})` which sends the correct request to GitHub’s REST API. 

The way this is implemented is by utilizing the `@octokit/octokit-rest-url-template` library internally [here](https://github.com/octokit/node-github/blob/677/rename-to-octokit-rest-clean/lib/endpoint/index.js#L28).
`@octokit/octokit-rest-url-template` could as well be part of the code base of `@octokit/rest` but I thought it would be useful by itself, hence a separate npm module which needs a separate repository.

I wondered if such a library makes sense to be part of the official Octokit toolkit, not only for Node but also for other languages, that’s why I opened this issue.

**Comment by kytrinyx** [comment]
> The JavaScript Rest library (@octokit/rest) has everything included.

Ok, so... if I'm understanding this correctly, you would parse the docs to figure out what parameters and options are available, and use the result to generate the library?



> I thought it would be useful by itself, hence a separate npm module which needs a separate repository.
> 
> I wondered if such a library makes sense to be part of the official Octokit toolkit, not only for Node but also for other languages, that’s why I opened this issue.

I'm not sure—the library is in JavaScript, but the other octokit clients would presumably use a URL template parsing library in the native language of the client, right?

Unless we're using the url template parser to generate some intermediate format that is language-agnostic. (I'm so sorry if I'm being dense about this—I'm still not convinced I actually understand the problem that you're describing!)

**Comment by gr2m** [comment]
> but the other octokit clients would presumably use a URL template parsing library in the native language of the client

Yes, the other libraries would use libraries in the respective language. 

For Node/JavaScript projects I’ve been several times in the situation where I needed a URL Template parsing library, and it was always because of an integration with GitHub. It would have helped me if there would be an "official" one I could trust, the existing ones usually worked but if this is a common requirement for integrators, I think it would be good if we had officially supported Octokit libraries for URL Template parsing for each language, or officially recommended ones from the community.

**Comment by gr2m** [comment]
Let me try to rephrase the my original question. I assume the other Octokit REST libraries (Ruby, .net, ...) implement URL Template parsing as specified in [RFC 6570](https://tools.ietf.org/html/rfc6570) internally. The Node library does not in its current form, but as part of my refactoring at https://github.com/octokit/node-github/pull/692, it does it internally. 

I was researching existing Node/JavaScript libraries for URL parsing and couldn’t find any that would return the list of variable names that have been used in parsing the URL template. So I created a new one: [`@octokit/rest-url-template`](https://github.com/gr2m/octokit-rest-url-template). While working on it I figured it makes sense to also

1. implement replacement of `:varname` which is not standards compliant
2. only implement the aspects of RFC 6570 that GitHub actually uses

I could have made the URL parsing just an internal implementation of the new Node library, but I figured it makes sense to make it a tiny standalone library as I have been in situations myself in the past where I could have used it to parse URLs from GitHub. So now the standalone URL template library exists at https://github.com/gr2m/octokit-rest-url-template and I wonder if we should make it "official" and move it to the @octokit GitHub organization or not.

This is all only relevant to JavaScript/Node, not to the other Octokit libraries. Unless we want to build similar libraries like https://github.com/gr2m/octokit-rest-url-template for ruby, .net, etc

**Comment by kytrinyx** [comment]
This is all making sense now! Thank you 🌻

For what it's worth, Octokit.rb relies on a 3rd party library for parsing URI templates.

> It would have helped me if there would be an "official" one I could trust

If GitHub follows the RFC, then it seems like any library that implements that RFC should work. I feel like the core problem here is that GitHub is doing things that are non-standard.

Can we identify all the places where we're deviating from the standard? If so I will raise this internally and work towards fixing it.

**Comment by gr2m** [comment]
I’ve created a [How it works](https://github.com/octokit/node-github/blob/677/rename-to-octokit-rest-clean/HOW_IT_WORKS.md) for the new JavaScript REST Octokit which might be helpful to put this issue into perspective. The URL parsing is part of step 6 of the lifecycle

[![image](https://user-images.githubusercontent.com/39992/34899435-b8cf54bc-f7ad-11e7-8a5e-bd5c3f3e8097.png)](https://github.com/octokit/node-github/blob/677/rename-to-octokit-rest-clean/HOW_IT_WORKS.md)

Thanks again for the great discussion. My conclusion is not to publish an official JavaScript URL Template parsing library but have another look at the existing solutions and see if we can incorporate the return of used parameters into them. Within the JavaScript REST Octokit I will replace `:varname` with `{varname}` before passing it to an RFC-compatible URL template parsing library.

> Can we identify all the places where we're deviating from the standard? If so I will raise this internally and work towards fixing it.

I will make a separate issue to discuss replacing `:varname` with `{varname}` in the v3 REST API docs at https://developer.github.com/v3/
