### ISSUE TITLE
v3 REST API: replace :varname with {varname} in endpoint route docs

### ISSUE THREAD

**Issue by gr2m** [octokit/discussions#18]
follow up for https://github.com/octokit/discussions/issues/17#issuecomment-357383761

# Example: [List organization repositories](https://developer.github.com/v3/repos/#list-organization-repositories)

I would suggest to change

```
GET /orgs/:org/repos
```

to 

```
GET /orgs/{org}/repos
```

to make it a valid URL Template as per [RFC 6570](https://tools.ietf.org/html/rfc6570).
This would be more coherent with the [hypermedia links returned by the API](https://developer.github.com/v3/#hypermedia).

**Comment by kytrinyx** [comment]
I submitted this for discussion to the docs team, and the initial impression is positive. I'm going to go ahead and close this one, as there's nothing further actionable on our end.

**Comment by gr2m** [comment]
thanks :) keep us posted
