### ISSUE TITLE
Add me to octokit GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [octokit/discussions#20]
Hey,

I am really excited about the active development and wanted to be a part of the **octokit** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is **YoginthS**

Thanks, Yoginth

**Comment by kytrinyx** [comment]
Hi @YoginthS 👋,

Thanks so much for your interest in contributing to Octokit!

The best way to get involved is to simply get started: find an issue and submit a pull request! You don't need to be a member of the organization to do so. 🌷
