### ISSUE TITLE
How to handle "ENOTFOUND api.github.com" responses

### ISSUE THREAD

**Issue by gr2m** [octokit/discussions#25]
I’m looking into implementing [best practises](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits) right into octokit.js as much as possible, like limiting mutating requests to 1 per second by default.

When I looked into the logs of the [WIP app](https://github.com/apps/wip), I’ve found that while there are plenty "You have triggered an abuse detection mechanism" errors, there are many more errors like this

> request to https://api.github.com/repos/gr2m/sandbox/statuses/b2d29b79ad66e9fc589e0c9f73319b2f5293d4fa failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443

![image](https://user-images.githubusercontent.com/39992/46911620-6f663700-cf16-11e8-8a23-8611027b0bc0.png)

Is that something any of you encountered before? Might it be a problem with [now](https://zeit.co/now)? Would you implement a retry for that error directly into the library?

**Comment by bkeepers** [comment]
`ENOTFOUND` is a DNS resolution error. I have rarely seen it in the apps I operate. I would definitely contact Zeit about it.
