### ISSUE TITLE
Where to direct support requests

### ISSUE THREAD

**Issue by kytrinyx** [octokit/discussions#5]
I've been reading through the open issues in the octokit library, and it looks like we're getting a fair number of support requests. Is this the right place for them? If not, what is a better place?

I'd suggest the platform.github.community forum, but that seems to be directed at the APIs and various types of GitHub integrations.

**Comment by bkeepers** [comment]
http://github.com/contact might be the best place for now.

**Comment by kytrinyx** [comment]
Thanks, that works for me 👍
