### ISSUE TITLE
Webhook support in octokit.js

### ISSUE THREAD

**Issue by bkeepers** [octokit/discussions#9]
We recently adopted `node-github` and will be renaming it to `octokit.js` in the coming months (#1). As part of that effort, we'd like to include webhook support in `octokit.js`.

https://github.com/rvagg/github-webhook-handler is the defacto module for node. @rjz has been maintaining it lately, but can't actually release new versions because he doesn't have access to the npm module from @rvagg. I'd like to propose that we fold it into `octokit.js`. There are still some things to figure out with how `octokit.js` will be structured with regard to plugins like this, but I imagine it will work something like this from an enduser's perspective:

1. `$ npm install octokit` will install all of octokit with all dependencies, and `require('octokit).webhooks` will give you access to the webhooks module
1. `$ npm install @octokit/webhooks` will install just the webhooks module, and `require('@octokit/webhooks')` will give you access to it.

Thoughts?

I've forked it to [octokit.js-webhooks](https://github.com/octokit/octokit.js-webhooks) and started submitting some PRs. I will work with @gr2m to figure out the plan for getting it released along with `octokit.js`.

cc @rjz @zeke @gr2m

**Comment by bkeepers** [comment]
Sorry, submitted too soon, so I'll update the OP with:

https://github.com/rvagg/github-webhook-handler is the defacto module for node. @rjz has been maintaining it lately, but can't actually release new versions because he doesn't have access to the npm module from @rvagg. I'd like to propose that we fold it into `octokit.js`. There are still some things to figure out with how `octokit.js` will be structured with regard to plugins like this, but I imagine it will work something like this from an enduser's perspective:

1. `$ npm install octokit` will install all of octokit with all dependencies, and `require('octokit).webhooks` will give you access to the webhooks module
1. `$ npm install @octokit/webhooks` will install just the webhooks module, and `require('@octokit/webhooks')` will give you access to it.

Thoughts?

I've forked it to [octokit.js-webhooks](https://github.com/octokit/octokit.js-webhooks) and started submitting some PRs. I will work with @gr2m to figure out the plan for getting it released along with `octokit.js`.

**Comment by rjz** [comment]
Seems reasonable to me. Excited to see node webhook support make its way into the octokit fold!

**Comment by gr2m** [comment]
I'd suggest for the time being, I'd rename the repository to just `webhooks.js`, make it a standalone repository and add issues. I'd name the package `@octokit/webhooks`.

I'm reluctant to make it part of `octokit` itself as I don't think it will be relevant for browser usage, while `octokit` should work in browsers, at least that's the plan so far. 

`npm install @octokit/webhooks` is the best approach.

**Comment by gr2m** [comment]
we have https://github.com/octokit/webhooks.js now
